apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgA+/QaPInYSO3Zj7hTmDZ8JgBaHZdTZIO1MiYUULUaSrgj9XjOBlMMu0Gb4p4Z/cxMerHgmJ7euYoMs84rQFN+HiRyU691F5Qht37pRWeP9s7jurNc6L6g1fIvaRgifzg9IetVr6I7PYaUNjFHFNhGuun3kN4NxFr/XOryq1W852Cqu2Fho0fLNBqhK2LbFat18ePKvFd+jdoJnX98EqfnUZlI0SvydnjpxVoks2leO68vJynLBC7Frr6+sGPhI4Ra9wh3unsdYT7KUbrMahMJGAKadHpbKSgc7YTz+SQnLWOLlik+1e2IZFWxSb35xLhz3mlNKJy8sNL9krZcW/ls8GeghZvlwzMGOk0W3lvVofaLcM7k11ZT9qxhwfRgzi8/OlAFxypeToj0iVfZI2BYeY+Y2E+bUsHH5wVA7NFX9ussWuHxSni+u3NJLm4KU2iI0a/iSKgoK1QeUISMA7qaBzxNmUO7Ap7Yfdzw74alHTHhtEHQlu7tOFfhtoEEGylaHeK9IHEYdDDze+sIxNMlKBpbM0GNOzRadfv+kpO960HW4WTIjPCiyAIPrN0amDcS89ULyz9EvkyD5g+GocIPD3KuLeNCAHDv+LGeymor7f1xoGGNEIE9K9ua/QNv0t7ORyGJsfKeq+Y+CiG6pWg8rK+3bOAvk0B23IzqVGcqM3N5LanSqjS6PfSvxBACkJIFCEt0t+PeSW5T8LnkuWAJZpCOvx8mMIJCI48KM670XIc0KP7r1Ztz4
    username: AgBMk188C8Ds8VgTqMkc3aW2CfeTkhhLyCKGnVNLLIGpe4KqLvIAxR+pA5Hrm/TXP55jyqHwiDZijZPAsgM/U40qgIH2GVOYrbBGs4Q+ptK4MJu3ryoIQsLyTysEcF2M1/3dpEQLhWPUu32MwSlEp/snxJIJD5gybzbtE8wVoCzPD0plI0jtGmf7I+rJUalbsTFT4HsAvhd1pgN1aV2Mbwa+EcO5cS0d+WfBiruFo+v03oCHy8bpByxJVfQqxBfnek/bPMGHvYdSVVBv2U0ZFEe0OUVYRVxOhBMzDT6DhREAZKJo+e0ZFKO5OVKgsc1JU4RDFQcRIGqL7dbEJQDna3dyX9GP5Zliap8BLUuhs/OQo3Wr3ORlRg02HkCxrhCnN1wmzS3YPNRBwoyiyljgtf1oaD2wGlV4n8TLJHqWO2moJ5zPokkkQ9upYajTF9tKkN/0O8SmDdC9sMZp+pyMd7T/51R/lzTwyiGd1Fa+f+TEvgzMkyQ1j2JHwDbZ3/hI7IJ75wQaFBfQ6HjAxXfjX4Ips2IT1NmnI436nW7Ezxsi0nptTLWmMJlCTdMgY5BzhotKRyEqvewihVV9DdHI6tZDP/nmRMnBaZTYeEwzxEo84iLKG/nZNkMHDtFXjIDRGrTDLRNsb4t28DQ2bDIi+or/e7eKCDqyQfVAGK9Rew3IE3owU0FIHUdQ5cReWOFLDihyQjzjQkc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

