apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBPD109ZGshEPDT8jyLRUPYJC9pPPjY83h+smHINVVmIJxz6V52sBkm4TZx8xNkjHtEB/mUTzz/HEKT09aQjiuELlMY/FJ97gjEKbSLobcRz9+hJE6/uRBAKQiV/xPp2YsGXgJfaCSGLl2Zeql3BTz381hm3Mun+ADr6Rs8o/aByhboJWVOY20xqmu50kS0LDBiSxk6V9EZqoiu0+T+Pd2rjhE0ztgHJVLl/OTrdRQPrxKdQALIT9ihJvVhHqtdRCDK3lKAdxOlLUWLkjnHA7X5E8zFxhCkiPCIymKhcYMYBVrQM6nLc/QiRpxVLfQzX3b0V2UmLvNA4aSxTyY9UOZVxLX0j/VXvsSEtS95xTd0BQIcmlhEKcwG3fyIINCb7oW4D/KYRCe1XCZYAY/7zzFVpsnbdsYO9Z3MZCinmJ7dVNP4QjkS6CE4Kb0pcir0u4kbz8l+/Qk9Jcs0/9/oU+z+g6smkHEO70mI4jCLE8YAyYQ0snb0DAoskYrf/W9fnPr4B2e/KbQq9HUiLIDVijmvTFezfBD/UyIf3NBcJiOR/V9DSd1Yzz4kclHA8n5hQfdhG0JkKju2ESCjAz3B2L24AiJZGxUJ/IBRRZRmHMBOd3al60PUe/9lRC/ktdO5H7FXIiTu7YRLxkk1JegPatPXgXXAwoiF9Yhc77i3JaYhrecfGBZ91hGnAEvhaC6DxnQZrzGyfsNyBPO/j741nXpi4YpnaTpZAkWUWCbUIMCoVkgokcpEZcWz
    username: AgBIwcvy+xOuOgUqo1d4+1Jbi4D/tQa4t0/bKsErWMiHKRDxRWPNdvVufr//diaO4D43btHWtoyeZcviWSUJ5QvAj+OJhQqUK/p9fvIJmBkN+vF0IhZ2RBLDfGGs+lMtoXJFKA4+xw0Vp2HSm8jPhjE5rsU3q0QmQcdBGwC4Olh1t1ndYHCT2QZRk1hvFEEPizECYEfVWtucgabqGfBuU2LiEwwjTbN9DNzaGFXSfsUaKFVrM203Sg6rUoZXB64GnMQ8BoXkN/HAH+OOV5ahTdE8I8ZCWFyazMqooZUXHzydnPsT91V4MQFKCZdT2oYp0Y+NDq0pasEcKcQ52iQt9CNc2dHP+3CqQOJoQuInNsikOMZvNxf5UcKP/37iodMlLo9+in8ZF/WgViW43wIagRLoUPhnuRzqUK3dsA+Ed9PreYd9nvxABFH8YaJpidm/GglHg+pWdcWpt2AyeRePZlwNRTa0+zRRWZm9jGPnrH88cWakAfUtghacXzGOv7hkHH0BJA4wTm8TM9eVigUxzHElVKsZm5yIjmeqLNsc3qHfWX6HbAB2fvokrMIxTf2EysCgDroqfYuq5JlwhTtmYE8D8gtiJlY3Re5seHsaRQN9jQLidIlH8tiqs05/V2yQeitoz/a0qT4q6A0XuY5CuwxM+88cjOW17wNCaysPnQf+yqgD5uGC3SAheFc/qOSzt1PScvjyUs0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

